name: browser_pup
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: siddharthborderwala <siddharthborderwala@users.noreply.github.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0
  puppeteer: ^1.13.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
